{
 "title": "OpenVPN Status OPNSENSE",
 "description": "Detalhe Status clientes conectados Openvpn",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dataAgora", "query": "${__from:date:seconds}" }
  ]
 },
 "panels": [
  {
   "title": "Clientes conectados",
   "type": "stat",
   "description": "Quantidade de usuários conectados",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(VirtualAddress) FROM \"openvpn-status\" WHERE time > now() - 1m ORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Clientes conectados atualmente",
   "type": "table",
   "description": "Lista os clientes conectados atualmente",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "clients_connect",
     "query": "SELECT CommonName, Username,RealAddress, VirtualAddress, ConnectedSince, ConnectedSince_t, LoginTime, BytesReceived, BytesSent FROM \"openvpn-status\" WHERE time > now() - 1m ORDER BY time DESC",
     "select": [
      [
       { "params": [ "cn" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conexão sem IP",
   "type": "stat",
   "description": "Quantidade de conexões sem Virtual IP",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(VirtualAddress) FROM \"openvpn-status\" WHERE VirtualAddress = '' AND time > now() - 1m ORDER BY time DESC"
    }
   ]
  }
 ]
}